/**
 * ERNAD MES - CENTRALIZED API CONTRACT
 * Single source of truth for all frontend-to-backend communication.
 * All paths are RELATIVE to the baseURL (http://localhost:4000/api/).
 * IMPORTANT: No leading slashes to prevent stripping the baseURL path.
 */

export const ENDPOINTS = {
  AUTH: {
    LOGIN: 'auth/login',
    LOGOUT: 'auth/logout',
    ME: 'auth/me',
    RESET_CREDENTIAL: 'auth/reset-credential',
  },
  TERMINALS: {
    OPERATORS: 'terminals/operators',
    AUTH_VERIFY: 'telemetry/verify-operator',
    AUTH_LOGIN: 'terminals/auth/login',
    REGISTER: 'terminals/register',
    STATE: (id: string) => `terminals/state/${id}`,
    ACTIVATE: 'terminals/activate',
  },
  OPERATOR_SESSIONS: {
    CURRENT: 'operator-sessions/current',
    RECENT: 'operator-sessions/recent',
    ACTIVE: 'operator-sessions/active',
    START: 'operator-sessions/start',
    END: 'operator-sessions/end',
    HEARTBEAT: 'operator-sessions/heartbeat',
    CHANGE_STATION: 'operator-sessions/change-station',
  },
  PRODUCTION: {
    BATCHES: 'production/batches',
    ACTIVE_BATCH: (lineId: string) => `production/active-batch/${lineId}`,
    START_BATCH: 'production/batches/start',
    CLOSE_BATCH: (id: string) => `production/batches/${id}/close`,
    REOPEN_BATCH: (id: string) => `production/batches/${id}/reopen`,
    APPROVE_BATCH: (id: string) => `production/batches/${id}/approve`,
    REQUEST_APPROVAL: (id: string) => `production/batches/${id}/request-approval`,
    REASSIGN_OPERATORS: (id: string) => `production/batches/${id}/reassign-operators`,
    ADJUST_TIME: (id: string) => `production/batches/${id}/adjust-time`,
    COMPLETE_CHANGEOVER: (id: string) => `production/batches/${id}/complete-changeover`,
    PACKAGING_LOGS: 'production/packaging-logs',
    DISPATCH_LOGS: 'production/dispatch-logs',
    LINE_CHANGEOVER: (id: string) => `production/lines/${id}/changeover`,
    TOGGLE_MAINTENANCE: (id: string) => `production/lines/${id}/toggle-maintenance`,
    LOGS: (type: string) => `production/logs/${type}`,
    LOGS_VERIFY: 'production/logs/:id/verify',
    LOGS_REJECT: 'production/logs/:id/reject',
    LOGS_CORRECT: 'production/logs/:id/correct',
  },
  INCIDENTS: {
    LIST: 'incidents',
    GET: (id: string) => `incidents/${id}`,
    CREATE: 'incidents',
    UPDATE: (id: string) => `incidents/${id}`,
    STATUS: (id: string) => `incidents/${id}/status`,
    COMMENTS: (id: string) => `incidents/${id}/comments`,
    ATTACHMENTS: (id: string) => `incidents/${id}/attachments`,
    TYPES: 'incidents/types',
    CREATE_TYPE: 'incidents/types',
    ANALYTICS: 'incidents/analytics',
  },
  TELEMETRY: {
    LOGS: 'telemetry/logs',
    OPERATOR_LOGS: 'telemetry/logs',
    VERIFY_OPERATOR: 'telemetry/verify-operator',
    HISTORY: (batchId: string, station: string) => `telemetry/history/${batchId}/${station}`,
    ACTIVE_EVENTS: (batchId: string) => `telemetry/active-events/${batchId}`,
    RECONCILIATION: (batchId: string) => `telemetry/reconciliation/${batchId}`,
    PATCH_LOG: (id: string) => `telemetry/logs/${id}`,
  },
  USERS: {
    LIST: 'users',
    AUDIT_LOGS: 'users/audit-logs',
    USER_AUDIT_LOGS: (id: string) => `users/${id}/audit-logs`,
    GET: (id: string) => `users/${id}`,
    CREATE: 'users',
    UPDATE: (id: string) => `users/${id}`,
    TOGGLE_ACTIVE: (id: string) => `users/${id}/toggle-active`,
    RESET_PIN: (id: string) => `users/${id}/reset-pin`,
    AVATAR: (id: string) => `users/${id}/avatar`,
  },
  INVENTORY: {
    LIST: 'inventory',
    STOCK: 'inventory/stock',
    STOCK_BY_CATEGORY: (category: string) => `inventory/stock/category/${category}`,
    ITEMS: 'inventory/items',
    CATEGORIES: 'inventory/categories',
    WAREHOUSES: 'inventory/warehouses',
    TRANSFERS: 'inventory/transfers',
    TRANSFER_COMPLETE: (id: string) => `inventory/warehousing/transfers/${id}/complete`,
    PACKAGING: (productId: string) => `inventory/packaging/${productId}`,
    LEDGER: (id: string) => `inventory/${id}/ledger`,
  },
  ANALYTICS: {
    KPIS: 'analytics/kpis',
    LINE_PERFORMANCE: 'analytics/line-performance',
    HISTORICAL: 'analytics/historical',
    FACTORY_LIVE: 'analytics/factory/live',
    FACTORY_EFFICIENCY: 'analytics/factory/efficiency',
  },
  MASTER_DATA: {
    LINES: 'master-data/lines',
    LINE: (id: string) => `master-data/lines/${id}`,
    BRANDS: 'master-data/brands',
    PRODUCTS: 'master-data/products',
    SHIFTS: 'master-data/shifts',
    SHIFT: (id: string) => `master-data/shifts/${id}`,
    RAW_MATERIALS: 'master-data/raw-materials',
  },
  BIOMETRIC: {
    DEVICES: 'biometric/devices',
    DEVICE: (id: string) => `biometric/devices/${id}`,
    TEST: (id: string) => `biometric/devices/${id}/test`,
    SYNC: (id: string) => `biometric/devices/${id}/sync`,
    LOGS: 'biometric/logs',
    UNMAPPED: 'biometric/unmapped',
    MAP_USER: 'biometric/map-user',
    ATTENDANCE_TODAY: 'biometric/attendance/today',
    ATTENDANCE: (id: string) => `biometric/attendance/${id}`,
    SHIFTS: 'biometric/shifts',
    ASSIGN_SHIFT: 'biometric/shifts/assign',
    REPORT_MONTHLY: 'biometric/reports/monthly',
  },
  NOTES: {
    LIST: 'notes',
    GET: (id: string) => `notes/${id}`,
    CREATE: 'notes',
    UPDATE: (id: string) => `notes/${id}`,
    DELETE: (id: string) => `notes/${id}`,
  },
  REPORTS: {
    SALES: 'reports/sales',
    PRODUCTION: 'reports/production',
    BATCHES: 'reports/batches',
    ATTENDANCE: 'reports/attendance',
    BATCH_DOSSIER: (id: string) => `reports/batch/${id}`,
  },
  TALLY: {
    SUMMARY: 'tally/summary',
  },
  NOTIFICATIONS: {
    UNREAD: 'notifications/unread',
    MARK_READ: (id: string) => `notifications/${id}/read`,
    TOKENS: 'notifications/tokens',
  },
  ATTENDANCE: {
    LIST: 'attendance/all',
    SYNC: 'attendance/sync',
    TODAY: 'biometric/attendance/today',
  }
};
